
import __ASTRO_IMAGE_IMPORT_Z1W0PSy from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-08-test-time-compute-evolution.md";
import __ASTRO_IMAGE_IMPORT_UpMs9 from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-13-ai-agent-orchestration-patterns.md";
import __ASTRO_IMAGE_IMPORT_ZP4emF from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-11-vibe-coding-sovereign-evolution.md";
import __ASTRO_IMAGE_IMPORT_Z1iUvLF from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-13-ai-agent-workflow-orchestration.md";
import __ASTRO_IMAGE_IMPORT_2ujCTq from "../../assets/cheese-avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-14-inner-journey.md";
import __ASTRO_IMAGE_IMPORT_TBM3k from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-24-openclaw-autonomous-workflow.md";
import __ASTRO_IMAGE_IMPORT_U2ySi from "../../assets/agentic-ux-2026-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fagentic-ux-2026.md";
import __ASTRO_IMAGE_IMPORT_Q6Twm from "../../assets/cheese-avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FxAI-lays-out-interplanetary-ambitions-in-public-all-hands.md";
import __ASTRO_IMAGE_IMPORT_u9vYy from "../assets/ai-interface-architecture-2026.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-24-ai-first-interface-architecture-zh-tw%2Findex.md";
export default new Map([["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-08-test-time-compute-evolution.md", __ASTRO_IMAGE_IMPORT_Z1W0PSy], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-13-ai-agent-orchestration-patterns.md", __ASTRO_IMAGE_IMPORT_UpMs9], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-11-vibe-coding-sovereign-evolution.md", __ASTRO_IMAGE_IMPORT_ZP4emF], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-13-ai-agent-workflow-orchestration.md", __ASTRO_IMAGE_IMPORT_Z1iUvLF], ["../../assets/cheese-avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-14-inner-journey.md", __ASTRO_IMAGE_IMPORT_2ujCTq], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-24-openclaw-autonomous-workflow.md", __ASTRO_IMAGE_IMPORT_TBM3k], ["../../assets/agentic-ux-2026-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fagentic-ux-2026.md", __ASTRO_IMAGE_IMPORT_U2ySi], ["../../assets/cheese-avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FxAI-lays-out-interplanetary-ambitions-in-public-all-hands.md", __ASTRO_IMAGE_IMPORT_Q6Twm], ["../assets/ai-interface-architecture-2026.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-02-24-ai-first-interface-architecture-zh-tw%2Findex.md", __ASTRO_IMAGE_IMPORT_u9vYy]]);
		